name: food_delivery_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.5.1
  firebase_core: ^0.7.0
  firebase_database: ^6.0.0
  firebase_storage: ^7.0.0
  flutter_staggered_animations: ^1.0.0
  font_awesome_flutter: ^8.11.0
  http: ^0.12.2
  lottie: ^0.7.0+1
  pedantic: ^1.11.0
  video_player: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/lottie/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Thin.otf
        - asset: assets/fonts/Gilroy-UltraLight.otf
        - asset: assets/fonts/Gilroy-Light.otf
        - asset: assets/fonts/Gilroy-Regular.otf
        - asset: assets/fonts/Gilroy-Medium.otf
        - asset: assets/fonts/Gilroy-SemiBold.otf
        - asset: assets/fonts/Gilroy-Bold.otf
        - asset: assets/fonts/Gilroy-ExtraBold.otf
        - asset: assets/fonts/Gilroy-Black.otf
        - asset: assets/fonts/Gilroy-Heavy.otf

